# Site Settings
#baseurl: "/Template-Bootstrap"
#url: "https://coolv1994.github.io"


# Site Info
#title: Bootstrap Template
#author: CoolV1994
#description: >
#  Bootstrap Template for GitHub Pages


# Custom Settings
encoding: utf-8
language: en
version: 1.0.0


# Markdown Processor
markdown: kramdown


# Sass/Scss Settings
sass:
    sass_dir: _sass


# Pagination Settings
paginate: 10
paginate_path: "/page/:num/"


# Include Files / Dirs
include:
  - _pages


# Excluded Files / Dirs
exclude: []


# Collection Settings
collections:
  blog:
    output: true
    url: /blog/
  docs:
    output: true
    url: /docs/
  examples:
    output: true
    url: /examples/


# Default Values
defaults:
  - scope:
      type: posts
    values:
      layout: PostLayout
  - scope:
      type: pages
    values:
      layout: PageLayout
  - scope:
      path: files
    values:
      album: files
  - scope:
      path: images
    values:
      album: images


# Plugin Settings
plugins: []


# Plugins (GH Pages)
#  - jekyll-coffeescript
#  - jekyll-default-layout
#  - jekyll-gist
#  - jekyll-github-metadata
#  - jekyll-optional-front-matter
#  - jekyll-paginate
#  - jekyll-readme-index
#  - jekyll-titles-from-headings
#  - jekyll-relative-links

