# Site Settings
baseurl: "/Template-Bootstrap"
url: "https://coolv1994.github.io"


# Site Info
title: Bootstrap Template
author: CoolV1994
description: >
  Bootstrap Template for GitHub Pages


# Custom Settings
version: 1.0.0
language: en


# Markdown Processor
markdown: kramdown


# Sass/Scss Settings
sass:
    sass_dir: _sass


# Pagination Settings
paginate: 10
paginate_path: "/page/:num/"


# Include Directories
include:
  - _pages


# Collection Settings
collections:
  blog:
    output: true
    url: /blog/
  docs:
    output: true
    url: /docs/
  examples:
    output: true
    url: /examples/


# Default Values
defaults:
  - scope:
      type: posts
    values:
      layout: PostLayout
  - scope:
      type: pages
    values:
      layout: PageLayout
  - scope:
      path: files
    values:
      album: files
  - scope:
      path: images
    values:
      album: images
